name: PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  phplint:
    name: PHP Lint
    uses: ./.github/workflows/test-shallow-clone-source-code.yml
    with:
      php-version: '["8.2", "8.3", "8.4"]'
      os: '["ubuntu-latest"]'
    secrets: inherit

  tests-exists:
    runs-on: ubuntu-latest
    name: tests-exists
    outputs:
      has-tests: ${{ steps.check.outputs.exists }}
      # steps.{ID}.outputs.{OUTPUT_NAME}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check directory
        id: check
        run: |
          if [ -d "tests" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  phpunit:
    needs: tests-exists
    if: needs.tests-exists.outputs.has-tests == 'true'
#    needs.{JOB_NAME}.outputs.{JOB_OUTPUT}
    uses: ./.github/workflows/phpunit.yml
    with:
      php-version: '["8.2", "8.3", "8.4"]'
      os: '["ubuntu-latest"]'
    secrets: inherit