name: PHP

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '["8.2", "8.3", "8.4"]'


jobs:
#  build:
#    runs-on: ${{ matrix.os }}
##    runs-on: ubuntu-latest
#
#    strategy:
#      fail-fast: false
#      matrix:
#        php: ${{ fromJson(inputs.phpVersions) }}
#        os: ['ubuntu-latest']
#
#    steps:
#      - name: Checkout code base
#        uses: actions/checkout@v4


  phplint:
    strategy:
      matrix:
        php: ${{ fromJson(inputs.php-version) }}
    name: PHP Lint
    uses: ./.github/workflows/test-phplint.yml #uses funktioniert nur auf joblevel nicht auf step
    with:
      php-version: ${{ matrix.php }}
#      os: ["ubuntu-latest"]
    secrets: inherit

#  tests-exists:
#    runs-on: ubuntu-latest
#    name: tests-exists
#    outputs:
#      has-tests: ${{ steps.check.outputs.exists }}
#      # steps.{ID}.outputs.{OUTPUT_NAME}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Check directory
#        id: check
#        run: |
#          if [ -d "tests" ]; then
#            echo "exists=true" >> $GITHUB_OUTPUT
#          else
#            echo "exists=false" >> $GITHUB_OUTPUT
#          fi
#
#  phpunit:
#    needs: tests-exists
#    if: needs.tests-exists.outputs.has-tests == 'true'
#  #    needs.{JOB_NAME}.outputs.{JOB_OUTPUT}
#    uses: ./.github/workflows/phpunit.yml
#    with:
#      php-version: ${{ inputs.php-version }}
#      os: '["ubuntu-latest"]'
#    secrets: inherit