name: PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  php-version-config:
      runs-on: ubuntu-latest
      outputs:
        php-version: ${{ steps.config.outputs.php-version }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: '1'
        - name: Load PHP version configuration
          id: config
          run: |
            php-version=$(jq -c 'php-versions' .github/php-version-config.json)
            echo "php-version=$php-version" >> $GITHUB_OUTPUT

  phplint:
    needs: php-version-config
    name: PHP Lint
    uses: ./.github/workflows/test-phplint.yml
    with:
      php-version: ${{ needs.php-version-config.outputs.php-version }}
#      os: '["ubuntu-latest"]'
    secrets: inherit

  tests-exists:
    runs-on: ubuntu-latest
    name: tests-exists
    outputs:
      has-tests: ${{ steps.check.outputs.exists }}
      # steps.{ID}.outputs.{OUTPUT_NAME}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - name: Check directory
        id: check
        run: |
          if [ -d "tests" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  phpunit:
    needs: [tests-exists, php-version-config]
    if: needs.tests-exists.outputs.has-tests == 'true'
#    needs.{JOB_NAME}.outputs.{JOB_OUTPUT}
    uses: ./.github/workflows/phpunit.yml
    with:
      php-version: ${{ needs.php-version-config.outputs.php-version }}
#      os: '["ubuntu-latest"]'
    secrets: inherit