name: PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  phplint:
    name: PHP Lint
    uses: ./.github/workflows/test-shallow-clone-source-code.yml
    with:
      php-version: '["8.2", "8.3", "8.4"]'
      os: '["ubuntu-latest"]'
    secrets: inherit

  phpunit:
    if:  hashFiles('tests/') != ''
    uses: ./.github/workflows/phpunit.yml
    with:
      php-version: '["8.2", "8.3", "8.4"]'
      os: '["ubuntu-latest"]'
    secrets: inherit