name: Unit Tests

on:
  workflow_call:
    inputs:
      php-version:
        type: string
      os:
        type: string

jobs:
    test:
      name: Unit tests with php ${{ inputs.php-version }}
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code base
          uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ inputs.php-version }}
            tools: phpunit

        - name: Setup Icinga Web
          run: |
            git clone --depth 1 https://github.com/Icinga/icingaweb2.git _icingaweb2
            ln -s `pwd` _icingaweb2/modules/icingadb

        - name: Setup Libraries
          run: |
            mkdir _libraries
            git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-library.git _libraries/ipl
            git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-thirdparty.git _libraries/vendor

        - name: PHPUnit
          env:
            ICINGAWEB_LIBDIR: _libraries
          run: phpunit --bootstrap _icingaweb2/test/php/bootstrap.php